version:  '3.1'

services:

 spring-app:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: spring-app
  ports:
   - "8080:8080"
  environment:
   - SPRING_PROFILES_ACTIVE=mysql
   
  volumes:
   - ./target:/app
   - uploads:/app/uploads
  depends_on:
   - db
  networks:
   - mynetwork
   
 db:
  image: mysql:8.0.31
  container_name: mysql-db
  ports:
   - "3307:3306"
  volumes:
   - db-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_DATABASE: siae
  networks:
   - mynetwork
   
 phpmyadmin:
  image: phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports: 
   - "8000:80"
  environment:
   PMA_HOST: db
   MYSQL_ROOT_PASSWORD: admin
  
volumes:
 db-data:
 uploads:
 
networks:
  mynetwork:
    driver: bridge