version:  '3.1'

services:

 spring-app:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: spring-app
  ports:
   - "8080:8080"
  environment:
   - SPRING_PROFILES_ACTIVE=mysql
   
  volumes:
   - ./target/siae-0.0.1-SNAPSHOT.jar:/app/app.jar
   - uploads:/app/uploads
  depends_on:
   - db
  networks:
   - mynetwork
   
   
 db:
  image: mysql:8.0.31
  container_name: mysql-db
  ports:
   - "3307:3306"
  volumes:
   - db-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_DATABASE: siae
  networks:
   - mynetwork
  healthcheck:
   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
   interval: 10s
   retries: 5
   start_period: 30s
   timeout: 10s
   
 phpmyadmin:
  image: phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports: 
   - "8000:80"
  environment:
   PMA_HOST: db
   MYSQL_ROOT_PASSWORD: admin
  networks:
   - mynetwork

 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq
  ports:
    - "5672:5672"      # Porta padrão usada pelo Spring
    - "15672:15672"    # Painel Web
  networks:
    - mynetwork
  
volumes:
 db-data:
 uploads:
 
networks:
  mynetwork:
    driver: bridge